### ISSUE TITLE
Use different user that default admin for login

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#184]
The default admin overrides on each start, so fhirUser is gone empty.
We need to fix it or use a different user that always will have fhirUser.

**Comment by ir4y** [comment]
```
fhirUser:
  id: admin
  resourceType: Practitioner
id: admin
resourceType: User
meta:
  lastUpdated: '2023-08-21T09:41:24.499291Z'
  createdAt: '2023-08-17T08:57:45.979649Z'
  versionId: '904'

```
