### ISSUE TITLE
Setup a local environment for the designer

### ISSUE THREAD

**Issue by dymio** [beda-software/fhir-emr#23]
Setup a local environment for the designer to give her ability to check the work.

**Comment by dymio** [comment]
I have fixed `Dockerfile` and prepared a special docker compose config for easy running the project local.

`docker-compose.local-run.yaml`:

```
version: '3.9'
services:
    webapp:
        image: fhir-emr/webapp
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TIER: local
        command: [ "yarn", "start" ]
        ports:
            - '3000:3000'
```

Command: `docker-compose -f docker-compose.yaml -f docker-compose.local-run.yaml up`
