### ISSUE TITLE
Creating a dynamic text is not possible

### ISSUE THREAD

**Issue by mlaletina95** [beda-software/fhir-emr#321]
Some questions contain placeholders that rely on the user's previous answers. 

For example:

- Regarding your use of (NAME THE SELECTED MEDICATION OR CLASS OF MEDICATIONS) over the past 12 months
- Have you found that you needed to take larger doses of (NAME THE SELECTED MEDICATION OR CLASS OF MEDICATIONS) to achieve the same effect as before?

Currently it's impossible to make `item.text` dynamic.

**Comment by mlaletina95** [comment]
It would be helpful if this extension https://build.fhir.org/ig/HL7/sdc/examples.html#using-text-and-cqf-expression is implemented.

**Comment by atuonufure** [comment]
![image](https://github.com/user-attachments/assets/73f016eb-14d3-416c-8fc0-bbf5e5752398)

**Comment by atuonufure** [comment]
Example
```yaml
  - text: What is your favorite beverage to drink?
    type: string
    linkId: beverageType
  
  - type: display
    linkId: result
    cqfExpression:
      language: text/fhirpath
      expression: >-
        'Your favorite drink: ' + %QuestionnaireResponse.item.where(linkId='beverageType').answer.value.string
```

**Comment by ruscoder** [comment]
The example is wrong. According to [the specification](https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-render.html
) it should be:

```yaml
item:
  - text: Default text
    _text:
      extension:
        - url: http://hl7.org/fhir/StructureDefinition/cqf-expression
           valueExpression:
             language: text/fhirpath
             expression: >-
               'Your favorite drink: ' + %QuestionnaireResponse.item.where(linkId='beverageType').answer.value.string
```
or in first class extension format:
```yaml
item:
  - text: Default text
    _text:
      cqfExpression:
        language: text/fhirpath
        expression: >-
          'Your favorite drink: ' + %QuestionnaireResponse.item.where(linkId='beverageType').answer.value.string
```


Examples of aidbox manifest using Attributes for first class extension (it's necessary for FHIR conversion)
```
"Questionnaire.item._text": {
                "path": ["item", "_text"],
                "resource": {"resourceType": "Entity", "id": "Questionnaire"},
            }, 
            "Questionnaire.item._text.extension": {
                "path": ["item", "_text", "extension"],
                "resource": {"resourceType": "Entity", "id": "Questionnaire"},
                "type": {"resourceType": "Entity", "id": "Extension"},
                "isCollection": True,
            }, 
            "Questionnaire.item._text.cqfExpression": {
                "path": ["item", "_text", "cqfExpression"],
                "resource": {"resourceType": "Entity", "id": "Questionnaire"},
                "type": {"resourceType": "Entity", "id": "Expression"},
                "description": "An expression that, when evaluated, provides the value for the element on which it appears.

",
                "extensionUrl": "http://hl7.org/fhir/StructureDefinition/cqf-expression",
            },
```
