### ISSUE TITLE
Unable to specify unit option

### ISSUE THREAD

**Issue by mlaletina95** [beda-software/fhir-emr#323]
- [x] Fix type for [unitOption](https://github.com/beda-software/fhir-emr/blob/master/contrib/aidbox-types/index.d.ts#L14210) it should be an array accordingly to FHIR specification.http://hl7.org/fhir/uv/sdc/behavior.html#unitOption
- [x] Fix value for QuestionQuantity control, it should be https://hl7.org/fhir/r4/datatypes.html#Quantity
- [x] Fix [QuestionQuantity](https://github.com/beda-software/fhir-emr/blob/master/src/components/BaseQuestionnaireResponseForm/widgets/number.tsx#L54-L74) controls to handle a list of unitOptions.
  - [x] Keep current behaviour if there is only one unitOption, but also set unit information in the control value
  - [x] Add select that allow to choose a unitOption from the provided list if there are more than one unitOption.
- [x] Add storybook for this control https://github.com/beda-software/fhir-emr/issues/291

Example of questionItem:
```
          - linkId: example
            text: example
            type: quantity
            unitOption:
              - Coding:
                  code: foot
                  system: http://unitsofmeasure.org
                  display: ft
              - Coding:
                  code: inch
                  system: http://unitsofmeasure.org
                  display: in
              - Coding:
                  code: cm
                  system: http://unitsofmeasure.org
                  display: cm
```

**Comment by atuonufure** [comment]
```yaml
resourceType: Questionnaire
item:
  - text: example-1
    type: quantity
    linkId: example-1
    unitOption:
      - code: foot
        system: http://unitsofmeasure.org
        display: ft
      - code: inch
        system: http://unitsofmeasure.org
        display: in
      - code: cm
        system: http://unitsofmeasure.org
        display: cm
```
