### ISSUE TITLE
SubQuestionnaire does not open within SubQuestionnaire

### ISSUE THREAD

**Issue by mlaletina95** [beda-software/fhir-emr#341]
**Description:**
The subQuestionnaire feature does not work when nesting one subQuestionnaire within another subQuestionnaire. 
When trying to open a subQuestionnaire inside another subQuestionnaire, the system fails to load the nested 
subQuestionnaire properly.

**Steps to Reproduce:**

1. Create a parent Questionnaire with a subQuestionnaire reference.
2. Nest a second Questionnaire inside the parent as a subQuestionnaire.
3. Try to open or access the nested subQuestionnaire.

**Examples:**

Example 1:

```
item:
  - linkId: questionnaire-example-q-1
    type: group
    item:
      - linkId: example-1
        text: 1. Example
        type: choice
        answerOption:
          - value:
              Coding:
                code: '1'
                display: '1'
          - value:
              Coding:
                code: '2'
                display: '2'
          - value:
              Coding:
                code: '3'
                display: '3'
meta:
  profile:
    - https://beda.software/beda-emr-questionnaire
status: active
resourceType: Questionnaire
id: q1
```

Example 2:

```
item:
  - linkId: questionnaire-example-q-2
    type: group
    item:
      - linkId: example-2
        text: 2. Example
        type: choice
        answerOption:
          - value:
              Coding:
                code: '1'
                display: '1'
          - value:
              Coding:
                code: '2'
                display: '2'
          - value:
              Coding:
                code: '3'
                display: '3'
  - linkId: questionnaire-example-q-1
    type: group
    item:
      - linkId: example-1
        type: group
        subQuestionnaire: q1
meta:
  profile:
    - https://beda.software/beda-emr-questionnaire
status: active
resourceType: Questionnaire
id: q2
```

Example 3:

```
item:
  - linkId: questionnaire-example-q-3
    type: group
    item:
      - linkId: example-3
        text: 3. Example
        type: choice
        answerOption:
          - value:
              Coding:
                code: '1'
                display: '1'
          - value:
              Coding:
                code: '2'
                display: '2'
          - value:
              Coding:
                code: '3'
                display: '3'
  - linkId: questionnaire-example-q-2
    type: group
    item:
      - linkId: example-2
        type: group
        subQuestionnaire: q2
meta:
  profile:
    - https://beda.software/beda-emr-questionnaire
status: active
resourceType: Questionnaire
id: q3
```

**Expected behavior:**
The nested subQuestionnaire should load correctly when referenced inside another subQuestionnaire

**Actual behavior:**
The subQuestionnaire does not open when nested
