### ISSUE TITLE
Implement input-inside-text group control

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#344]
As an enhancement for https://github.com/beda-software/fhir-emr/issues/329
We need to introduce itemControl for a group that place children items inside a text.
Child items can't be groups, it should be a plain list if items:
```yaml
item:
- linkId: text
   itemControl:
     coding:
        - code: inputs-inside-text
   type: group
   text: |
     By signing this form, I voluntarily authorize <input linkId="subject"/> to release my radiographic
     breast cancer imaging and related health information taken from  <input linkId="object"/> at <input linkId="date"/>.
  item:
  - linkId: subject
     type: string
  - linkId: object
     type: string
  - linkId: date
     type: dateTime
```
