### ISSUE TITLE
Data loss in repeatable group form items

### ISSUE THREAD

**Issue by qscgyjqscgyj** [beda-software/fhir-emr#410]
Questionnaire:

```
item:
  - linkId: conditions-group
    text: Conditions
    type: group
    item:
      - linkId: conditions-details-group
        type: group
        repeats: true
        item:
          - linkId: condition-type
            text: Disease/Condition
            type: choice
            required: true
            answerValueSet: http://hl7.org/fhir/ValueSet/condition-code
          - linkId: condition-status
            text: Status
            type: choice
            answerOption:
              - value:
                  Coding:
                    system: "http://loinc.org"
                    code: "LA16666-2"
                    display: Current
              - value:
                  Coding:
                    system: "http://loinc.org"
                    code: "LA18632-2"
                    display: Past
          - linkId: condition-notes
            text: Notes
            type: string
meta:
  profile:
    - https://beda.software/beda-emr-questionnaire
name: Conditions
title: Conditions
status: active
subjectType:
  - Encounter
  - Patient
mapping:
  - id: conditions-create
    resourceType: Mapping
useContext:
  - code:
      code: questionnaire-type
      system: https://rce.uoh.cl/FHIR/CodeSystem/questionnaire-type
    value:
      CodeableConcept:
        coding:
          - code: clinical-form
resourceType: Questionnaire
id: conditions
```

Problem:
If we fill 1st form group and add new one and fill it after and add one more and fill it the result questionnaire response will include only 1st and 3rd groups, but if we firstly add 3 groups before and fill it after, whole groups data will be in the result quuestionnaire response

https://github.com/user-attachments/assets/19e49c6d-b529-4efc-836e-5c729343ca30
