### ISSUE TITLE
Item field text is not displayed when using "markdown-editor" itemControl

### ISSUE THREAD

**Issue by alexlipovka** [beda-software/fhir-emr#419]
Steps to reproduce:

Add itemControl to "text" or "string" field:
```yaml
- linkId: notes
  text: Notes
  type: text
  itemControl:
    coding:
      - code: markdown-editor
```

Expected that "Notes" title will be rendered above markdown editor control, but it does not
