### ISSUE TITLE
itemControl.coding.code.inline-choice does not work in a wizard group

### ISSUE THREAD

**Issue by mlaletina95** [beda-software/fhir-emr#437]
**Preconditions:**

1. Create a questionnaire with a wizard group.
2. Add itemControl.coding.code.inline-choice to the questionnaire.

**Steps to Reproduce:**
1. Navigate to the questionnaire using the wizard group.

Example: 

```
item:
  - linkId: medical-history-wizard-group
    type: group
    itemControl:
      coding:
        - code: wizard
    item:
      - linkId: medical-history-and-health-group
        text: Medical history and health
        type: group
        item:
          - linkId: mood-swings
            text: Mood swings
            type: choice
            itemControl:
              coding:
                - code: inline-choice
            answerOption:
              - value:
                  Coding:
                    system: "http://loinc.org"
                    code: "LA4489-6"
                    display: "No data"
      - linkId: anamnesis-and-lifestyle-group
        text: Anamnesis and lifestyle
        type: group
        item:
          - linkId: allergies-group
            text: Allergies
            type: group
            item:
              - linkId: patient-has-allergies
                text: Does the patient have any allergies?
                type: choice
                answerOption:
                  - value:
                      Coding:
                        system: "http://loinc.org"
                        code: "LA33-6"
                        display: "Yes"
              - linkId: allergies-details
                type: string
                enableWhen:
                  - question: patient-has-allergies
                    operator: "="
                    answer:
                      Coding:
                        code: "LA33-6"
meta:
  profile:
    - https://beda.software/beda-emr-questionnaire
name: Medical History
title: Medical History
status: active
subjectType:
  - Encounter
  - Patient
resourceType: Questionnaire
id: wizard-inline-choice-bug
```

**Expected Result:**
The navigation works successfully without any issues.

**Actual Result:**
The navigation fails and a white screen appears.

**Additional Description:**
When the enableWhen condition is commented out everything works correctly.
