### ISSUE TITLE
Implement WHR HMB Questionnaire

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-emr#511]
Source file: [WHR HMB Questionnaire.pdf](https://github.com/user-attachments/files/20514160/WHR.HMB.Questionnaire.pdf)

WIP:

Questionnaire source [q.json](https://github.com/user-attachments/files/20514176/q.json) 

Loaded to aidbox: https://aidbox.emr.beda.software/ui/console#/resources-v2/Questionnaire?_count=30&_page=1&_sort=_id&_ilike=hmb&__selected=547eaa1d-63ed-47d5-87a8-51a119d482d2

Page in EMR: https://emr.beda.software/patients/patient1/documents/new/547eaa1d-63ed-47d5-87a8-51a119d482d2

**Comment by kozlovana** [comment]
@ir4y 
WIP: https://aidbox.emr.beda.software/ui/console#/entities/Questionnaire/heavy-menstrual-bleeding?
https://emr.beda.software/patients/patient1/documents/new/heavy-menstrual-bleeding

**Comment by kozlovana** [comment]
[Added heavy-menstrual-bleeding questionnaire #513](https://github.com/beda-software/fhir-emr/pull/513)

Changed gtable to a simple repeatable group using:
```
extension:
  - url: http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl
    valueCodeableConcept:
      coding:
        - code: row
```
Also added more row groups to fields to make the questionnaire more compact
